name: Principis
favicon: null
layout_spectrum: 0.3979
typography_spectrum: 0.80051
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#882d68'
    - '#313191'
    - '#000000'
    - '#ff0000'
    - '#0000ff'
  brandStrength: 0.625
  lightness: 0.22548138722777367
  saturation: 0.5
  rhythmicContrast: 0.39150949264876544
purpose: []
