name: Principis Ltd
favicon: null
layout_spectrum: 0.64046
typography_spectrum: 0.83013
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#902c63'
    - '#05002e'
    - '#ba5f7f'
    - '#ffffff'
    - '#ff0000'
  brandStrength: 0.3125
  lightness: 0.3125
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
